/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;
import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noway
 */
public class drugUI extends javax.swing.JFrame {

    private static int control;
    /**
     * Creates new form drugUI
     */
    public drugUI(int control) {
        initComponents();
        setControl(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchButt = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        ammountField = new javax.swing.JTextField();
        expField = new javax.swing.JTextField();
        infoField = new javax.swing.JTextField();
        howToField = new javax.swing.JTextField();
        sideEffectField = new javax.swing.JTextField();
        companyField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        addButt = new javax.swing.JButton();
        updateButt1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        showButt = new javax.swing.JButton();
        deleteButt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        backbutt = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Position");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 800));

        searchButt.setBackground(new java.awt.Color(8, 119, 191));
        searchButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButt.setForeground(new java.awt.Color(255, 255, 255));
        searchButt.setText("search");
        searchButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        nameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        priceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        priceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceFieldKeyTyped(evt);
            }
        });

        ammountField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ammountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ammountFieldKeyTyped(evt);
            }
        });

        expField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        expField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expFieldKeyTyped(evt);
            }
        });

        infoField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                infoFieldKeyTyped(evt);
            }
        });

        howToField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        howToField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                howToFieldKeyTyped(evt);
            }
        });

        sideEffectField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        companyField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(150, 217, 207));

        addButt.setBackground(new java.awt.Color(8, 119, 191));
        addButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButt.setForeground(new java.awt.Color(255, 255, 255));
        addButt.setText("ADD");
        addButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtActionPerformed(evt);
            }
        });

        updateButt1.setBackground(new java.awt.Color(8, 119, 191));
        updateButt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButt1.setForeground(new java.awt.Color(255, 255, 255));
        updateButt1.setText("UPDATE");
        updateButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButt1ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(8, 119, 191));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        showButt.setBackground(new java.awt.Color(8, 119, 191));
        showButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showButt.setForeground(new java.awt.Color(255, 255, 255));
        showButt.setText("SHOW");
        showButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtActionPerformed(evt);
            }
        });

        deleteButt.setBackground(new java.awt.Color(8, 119, 191));
        deleteButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButt.setForeground(new java.awt.Color(255, 255, 255));
        deleteButt.setText("DELETE");
        deleteButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(updateButt1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deleteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(showButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButt)
                    .addComponent(updateButt1)
                    .addComponent(clear)
                    .addComponent(showButt)
                    .addComponent(deleteButt))
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Ammount In Packs", "Exp.Date", "Company", "Side Effect", "How To Use", "Further Info"
            }
        ));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exp.Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ammount In Packs");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Company");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Side Effect");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("How To Use");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Further Info");

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));

        backbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icon.png"))); // NOI18N
        backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(searchButt)
                        .addGap(81, 81, 81)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(priceField)
                    .addComponent(ammountField)
                    .addComponent(expField))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel7))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(sideEffectField)
                            .addComponent(howToField)
                            .addComponent(infoField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchButt)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ammountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(companyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sideEffectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(howToField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(49, 49, 49)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void close() { 
    this.setVisible(false);
    this.dispose();
    }
    public void setControl(int control){
        this.control = control;
    }
    public int getControl(){
        return control;
    }
    
    private void searchButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtActionPerformed
        String name = searchField.getText();
        drugLinkedList list = new drugLinkedList();
        drug dr = list.searchList(name);
        if(list.getCounter()==0){
            JOptionPane.showMessageDialog(null, "add item first to search", "pharamacy managmnt system", JOptionPane.OK_OPTION);
        }
        else{
            if(dr==null){
                JOptionPane.showMessageDialog(null, "no items found by this name", "pharamacy managmnt system", JOptionPane.OK_OPTION);
            }
            else{
                nameField.setText(dr.getName());
                priceField.setText(String.valueOf(dr.getPrice()));
                ammountField.setText(String.valueOf(dr.getAmountInPacks()));
                expField.setText(dr.getExpDate());
                companyField.setText(dr.getCompany());
                sideEffectField.setText(dr.getSideEffect());
                howToField.setText(dr.getHowTo());
                infoField.setText(dr.getInfo());
            }
        }
    }//GEN-LAST:event_searchButtActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        char c = evt.getKeyChar();
            if(Character.isDigit(c)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void priceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceFieldKeyTyped
        char c = evt.getKeyChar();
            if(!(Character.isDigit(c)||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_priceFieldKeyTyped

    private void expFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expFieldKeyTyped
        
    }//GEN-LAST:event_expFieldKeyTyped

    private void infoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_infoFieldKeyTyped
        
    }//GEN-LAST:event_infoFieldKeyTyped

    private void howToFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_howToFieldKeyTyped
        
    }//GEN-LAST:event_howToFieldKeyTyped

    private void addButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        
        if(nameField.getText().equals("")||priceField.getText().equals("")||ammountField.getText().equals("")||expField.getText().equals("")
                 ||companyField.getText().equals("")||sideEffectField.getText().equals("")||howToField.getText().equals("")||infoField.getText().equals("")){
            errorLabel.setText("Error: every field must be field approperietly");
        }
       else{
            String name = nameField.getText();
            float price = Float.parseFloat(priceField.getText());
            int ammount = Integer.parseInt(ammountField.getText());
            String exp = expField.getText();
            String company = companyField.getText();
            String sideEffect = sideEffectField.getText();
            String howTo = howToField.getText();
            String info = infoField.getText();
            
            drug dr = new drug(name,price,ammount,exp,company,sideEffect,howTo,info);
            dr.addDrugs(dr);
            model.addRow(new Object[]{name,price,ammount,exp,company,sideEffect,howTo,info});
        }
    }//GEN-LAST:event_addButtActionPerformed

    private void updateButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButt1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
              if(nameField.getText().equals("")||priceField.getText().equals("")||ammountField.getText().equals("")||expField.getText().equals("")
                 ||companyField.getText().equals("")||sideEffectField.getText().equals("")||howToField.getText().equals("")||infoField.getText().equals("")){
            errorLabel.setText("Error: every field must be field approperietly");
                }
              else{
                String name = nameField.getText();
                float price = Float.parseFloat(priceField.getText());
                int ammount = Integer.parseInt(ammountField.getText());
                String exp = expField.getText();
                String company = companyField.getText();
                String sideEffect = sideEffectField.getText();
                String howTo = howToField.getText();
                String info = infoField.getText();
                
                int row = jTable.getSelectedRow();
                //System.out.println(row);
                drug dr = new drug(name,price,ammount,exp,company,sideEffect,howTo,info);
                drugLinkedList list  = new drugLinkedList();
                list.update(row,dr);
            
                jTable.setValueAt(name,row,0);
                jTable.setValueAt(price,row,1);
                jTable.setValueAt(ammount,row,2);
                jTable.setValueAt(exp,row,3);
                jTable.setValueAt(company,row,4);
                jTable.setValueAt(sideEffect,row,5);
                jTable.setValueAt(howTo,row,6);
                jTable.setValueAt(info,row,7);
              } 
        }
    }//GEN-LAST:event_updateButt1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nameField.setText("");
        priceField.setText("");
        ammountField.setText("");
        expField.setText("");
        companyField.setText("");
        sideEffectField.setText("");
        howToField.setText("");
        infoField.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void showButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
           int x = jTable.getSelectedRow();
            nameField.setText(String.valueOf(jTable.getValueAt(x,0)));
            priceField.setText(String.valueOf(jTable.getValueAt(x,1)));
            ammountField.setText(String.valueOf(jTable.getValueAt(x,2)));
            expField.setText(String.valueOf(jTable.getValueAt(x,3)));
            companyField.setText(String.valueOf(jTable.getValueAt(x,4)));
            sideEffectField.setText(String.valueOf(jTable.getValueAt(x,5)));
            howToField.setText(String.valueOf(jTable.getValueAt(x,6)));
            infoField.setText(String.valueOf(jTable.getValueAt(x,7)));
        }
    }//GEN-LAST:event_showButtActionPerformed

    private void deleteButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
            drugLinkedList list = new drugLinkedList();
            list.deleteAt(jTable.getSelectedRow());
            model.removeRow(jTable.getSelectedRow());
            
        }
    }//GEN-LAST:event_deleteButtActionPerformed

    private void ammountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ammountFieldKeyTyped
        char c = evt.getKeyChar();
            if(!(Character.isDigit(c)||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_ammountFieldKeyTyped

    private void backbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttActionPerformed
        if(control==1){
            new ownerUI().setVisible(true);
            close();
        }
        else if(control==2){
            new pharmacistUI().setVisible(true);
            close();
        }
    }//GEN-LAST:event_backbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drugUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drugUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drugUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drugUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drugUI(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButt;
    private javax.swing.JTextField ammountField;
    private javax.swing.JButton backbutt;
    private javax.swing.JButton clear;
    private javax.swing.JTextField companyField;
    private javax.swing.JButton deleteButt;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField expField;
    private javax.swing.JTextField howToField;
    private javax.swing.JTextField infoField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JButton searchButt;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showButt;
    private javax.swing.JTextField sideEffectField;
    private javax.swing.JButton updateButt1;
    // End of variables declaration//GEN-END:variables
}
