/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author noway
 */
//getValueAt(int row, int column)
//model.insertRow(Integer.parseInt(kebeleField.getText()),new Object[]{null,null,null,null,null,null,null,null,null});
public class employeeUI extends javax.swing.JFrame {
    private static int control;
    /**
     * Creates new form employee
     */
    public employeeUI(int control) {
        initComponents();
        setControl(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        phoneNoField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        positionField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        workDaysField = new javax.swing.JTextField();
        salaryField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        kebeleField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        homeNoField = new javax.swing.JTextField();
        searchField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        jPanel2 = new javax.swing.JPanel();
        addButt = new javax.swing.JButton();
        updateButt1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        showButt = new javax.swing.JButton();
        deleteButt = new javax.swing.JButton();
        searchButt = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        backbutt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        phoneNoField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        idField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kebele Id");

        positionField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Position");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Work Days");

        workDaysField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        workDaysField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                workDaysFieldKeyTyped(evt);
            }
        });

        salaryField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salaryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                salaryFieldKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salary");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");

        emailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        kebeleField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kebeleField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kebeleFieldKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kebele");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home No");

        homeNoField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeNoFieldKeyTyped(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        nameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Position", "Salary", "Work Days", "Phone No", "Email", "Kebele", "Home No"
            }
        ));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jPanel2.setBackground(new java.awt.Color(150, 217, 207));

        addButt.setBackground(new java.awt.Color(8, 119, 191));
        addButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButt.setForeground(new java.awt.Color(255, 255, 255));
        addButt.setText("ADD");
        addButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtActionPerformed(evt);
            }
        });

        updateButt1.setBackground(new java.awt.Color(8, 119, 191));
        updateButt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButt1.setForeground(new java.awt.Color(255, 255, 255));
        updateButt1.setText("UPDATE");
        updateButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButt1ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(8, 119, 191));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        showButt.setBackground(new java.awt.Color(8, 119, 191));
        showButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showButt.setForeground(new java.awt.Color(255, 255, 255));
        showButt.setText("SHOW");
        showButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtActionPerformed(evt);
            }
        });

        deleteButt.setBackground(new java.awt.Color(8, 119, 191));
        deleteButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButt.setForeground(new java.awt.Color(255, 255, 255));
        deleteButt.setText("DELETE");
        deleteButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(updateButt1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deleteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButt)
                    .addComponent(updateButt1)
                    .addComponent(clear)
                    .addComponent(showButt)
                    .addComponent(deleteButt))
                .addContainerGap())
        );

        searchButt.setBackground(new java.awt.Color(8, 119, 191));
        searchButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButt.setForeground(new java.awt.Color(255, 255, 255));
        searchButt.setText("search");
        searchButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));

        backbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icon.png"))); // NOI18N
        backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(idField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7))
                                        .addGap(69, 69, 69))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(95, 95, 95)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phoneNoField, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(emailField)
                                        .addComponent(kebeleField))
                                    .addComponent(homeNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(210, 210, 210))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(searchButt)
                                .addGap(60, 60, 60)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salaryField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(workDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(218, 218, 218))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButt)
                    .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(phoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(kebeleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salaryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(homeNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workDaysField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close() { 
    this.setVisible(false);
    this.dispose();
    } 
    public void setControl(int control){
        this.control = control;
    }
    public int getControl(){
        return control;
    }
    
    private void addButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtActionPerformed
         if(nameField.getText().equals("")||idField.getText().equals("")||positionField.getText().equals("")||salaryField.getText().equals("")
                 ||workDaysField.getText().equals("")||phoneNoField.getText().equals("")||emailField.getText().equals("")||kebeleField.getText().equals("")
                 ||homeNoField.getText().equals("")){
            errorLabel.setText("Error: every field must be field approperietly");
        }
       else{
        String name = nameField.getText();
        String id = idField.getText();
        String position = positionField.getText();
        int salary = Integer.parseInt(salaryField.getText());
        String workDays = workDaysField.getText();
        String phoneNo = phoneNoField.getText();
        String email = emailField.getText();
        int kebele = Integer.parseInt(kebeleField.getText());
        int homeNo = Integer.parseInt(homeNoField.getText());
       
        
            address addr = new address(phoneNo,email,kebele,homeNo);
            employee emp = new employee(name,id,position,salary,workDays,addr);
            emp.addEmployee(emp);
        
         DefaultTableModel model = (DefaultTableModel) jTable.getModel();
         
         model.addRow( new Object[]{nameField.getText(),idField.getText(),positionField.getText(),salaryField.getText(),workDaysField.getText(),
             phoneNoField.getText(),emailField.getText(),kebeleField.getText(),homeNoField.getText()});
         } 
    }//GEN-LAST:event_addButtActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
         char c = evt.getKeyChar();
            if(Character.isDigit(c)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void idFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldKeyTyped

    private void workDaysFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workDaysFieldKeyTyped
         char c = evt.getKeyChar();
            if(Character.isDigit(c)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_workDaysFieldKeyTyped

    private void salaryFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryFieldKeyTyped
        char c = evt.getKeyChar();
            if(!(Character.isDigit(c)||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_salaryFieldKeyTyped

    private void kebeleFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kebeleFieldKeyTyped
         char c = evt.getKeyChar();
            if(!(Character.isDigit(c)||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_kebeleFieldKeyTyped

    private void homeNoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeNoFieldKeyTyped
         char c = evt.getKeyChar();
            if(!(Character.isDigit(c)||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE)){
                getToolkit().beep();
                evt.consume();
            }
    }//GEN-LAST:event_homeNoFieldKeyTyped

    private void showButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
           int x = jTable.getSelectedRow();
            nameField.setText(String.valueOf(jTable.getValueAt(x,0)));
            idField.setText(String.valueOf(jTable.getValueAt(x,1)));
            positionField.setText(String.valueOf(jTable.getValueAt(x,2)));
            salaryField.setText(String.valueOf(jTable.getValueAt(x,3)));
            workDaysField.setText(String.valueOf(jTable.getValueAt(x,4)));
            phoneNoField.setText(String.valueOf(jTable.getValueAt(x,5)));
            emailField.setText(String.valueOf(jTable.getValueAt(x,6)));
            kebeleField.setText(String.valueOf(jTable.getValueAt(x,7)));
            homeNoField.setText(String.valueOf(jTable.getValueAt(x,8)));
        }
    }//GEN-LAST:event_showButtActionPerformed

    private void updateButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButt1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
              if(nameField.getText().equals("")||idField.getText().equals("")||positionField.getText().equals("")||salaryField.getText().equals("")
                 ||workDaysField.getText().equals("")||phoneNoField.getText().equals("")||emailField.getText().equals("")||kebeleField.getText().equals("")
                 ||homeNoField.getText().equals("")){
            errorLabel.setText("Error: every field must be field approperietly");
        }
              else{
                String name = nameField.getText();
                String id = idField.getText();
                String position = positionField.getText();
                int salary = Integer.parseInt(salaryField.getText());
                String workDays = workDaysField.getText();
                String phoneNo = phoneNoField.getText();
                String email = emailField.getText();
                int kebele = Integer.parseInt(kebeleField.getText());
                int homeNo = Integer.parseInt(homeNoField.getText());
                
                int row = jTable.getSelectedRow();
                //System.out.println(row);
                address addr = new address(phoneNo,email,kebele,homeNo);
                employee emp = new employee(name,id,position,salary,workDays,addr);
                employeeLinkedList list  = new employeeLinkedList();
                list.update(row,emp);
            
                jTable.setValueAt(name,row,0);
                jTable.setValueAt(id,row,1);
                jTable.setValueAt(position,row,2);
                jTable.setValueAt(salary,row,3);
                jTable.setValueAt(workDays,row,4);
                jTable.setValueAt(phoneNo,row,5);
                jTable.setValueAt(email,row,6);
                jTable.setValueAt(kebele,row,7);
                jTable.setValueAt(homeNo,row,8);
              }
            
        }
    }//GEN-LAST:event_updateButt1ActionPerformed

    private void deleteButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
            
            System.out.println(jTable.getSelectedRow());
            employeeLinkedList list = new employeeLinkedList();
            list.deleteAt(jTable.getSelectedRow());
            model.removeRow(jTable.getSelectedRow());
            
        }
    }//GEN-LAST:event_deleteButtActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nameField.setText("");
        idField.setText("");
        positionField.setText("");
        salaryField.setText("");
        workDaysField.setText("");
        phoneNoField.setText("");
        emailField.setText("");
        kebeleField.setText("");
        homeNoField.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void searchButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtActionPerformed
        String name = searchField.getText();
        employeeLinkedList list = new employeeLinkedList();
        employee emp = list.searchList(name);
        if(list.getCounter()==0){
            JOptionPane.showMessageDialog(null, "add item first to search", "pharamacy managmnt system", JOptionPane.OK_OPTION);
        }
        else{
        if(emp==null){
            JOptionPane.showMessageDialog(null, "no items found by this name", "pharamacy managmnt system", JOptionPane.OK_OPTION);
        }
        else{
            nameField.setText(emp.getName());
            idField.setText(emp.getId());
            positionField.setText(emp.getpostion());
            salaryField.setText(String.valueOf(emp.getSalary()));
            workDaysField.setText(emp.getWorkDays());
            phoneNoField.setText(emp.addr.getPhoneNumber());
            emailField.setText(emp.addr.getEmail());
            kebeleField.setText(String.valueOf(emp.addr.getKebele()));
            homeNoField.setText(String.valueOf(emp.addr.getHomeNumber()));
        }
        }
    }//GEN-LAST:event_searchButtActionPerformed

    private void backbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttActionPerformed
        if(control==1){
            new ownerUI().setVisible(true);
            close();
        }
        else if(control==2){
            new pharmacistUI().setVisible(true);
            close();
        }
    }//GEN-LAST:event_backbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeUI(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButt;
    private javax.swing.JButton backbutt;
    private javax.swing.JButton clear;
    private javax.swing.JButton deleteButt;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField homeNoField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField kebeleField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JTextField positionField;
    private javax.swing.JTextField salaryField;
    private javax.swing.JButton searchButt;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showButt;
    private javax.swing.JButton updateButt1;
    private javax.swing.JTextField workDaysField;
    // End of variables declaration//GEN-END:variables
}
