/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author noway
 */
public class patientUI extends javax.swing.JFrame {
    static private int control;
    /**
     * Creates new form patient
     */
    public patientUI(int control) {
        initComponents();
        setControl(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchButt = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        phoneNoField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        kebeleField = new javax.swing.JTextField();
        homeNoField = new javax.swing.JTextField();
        perscribedByField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        patientCaseField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addButt = new javax.swing.JButton();
        updateButt1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        showButt = new javax.swing.JButton();
        deleteButt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;
            }
        };
        drugField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        backbutt = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 800));

        searchButt.setBackground(new java.awt.Color(8, 119, 191));
        searchButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchButt.setForeground(new java.awt.Color(255, 255, 255));
        searchButt.setText("search");
        searchButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        phoneNoField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        emailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        kebeleField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kebeleField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kebeleFieldKeyTyped(evt);
            }
        });

        homeNoField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeNoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homeNoFieldKeyTyped(evt);
            }
        });

        perscribedByField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        perscribedByField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perscribedByFieldKeyTyped(evt);
            }
        });

        dateField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateField.setEnabled(false);
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        dateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateFieldKeyTyped(evt);
            }
        });

        patientCaseField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        idField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        idField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idFieldKeyTyped(evt);
            }
        });

        nameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient case");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perscribed By");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home No");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kebele");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone No");

        jPanel3.setBackground(new java.awt.Color(150, 217, 207));

        addButt.setBackground(new java.awt.Color(8, 119, 191));
        addButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addButt.setForeground(new java.awt.Color(255, 255, 255));
        addButt.setText("ADD");
        addButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtActionPerformed(evt);
            }
        });

        updateButt1.setBackground(new java.awt.Color(8, 119, 191));
        updateButt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateButt1.setForeground(new java.awt.Color(255, 255, 255));
        updateButt1.setText("UPDATE");
        updateButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButt1ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(8, 119, 191));
        clear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        showButt.setBackground(new java.awt.Color(8, 119, 191));
        showButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showButt.setForeground(new java.awt.Color(255, 255, 255));
        showButt.setText("SHOW");
        showButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtActionPerformed(evt);
            }
        });

        deleteButt.setBackground(new java.awt.Color(8, 119, 191));
        deleteButt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteButt.setForeground(new java.awt.Color(255, 255, 255));
        deleteButt.setText("DELETE");
        deleteButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(updateButt1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deleteButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(showButt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButt)
                    .addComponent(updateButt1)
                    .addComponent(clear)
                    .addComponent(showButt)
                    .addComponent(deleteButt))
                .addContainerGap())
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Patient Case", "Date", "Perscribed By", "Drug Bought", "Phone No", "Email", "Kebele", "Home No"
            }
        ));
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        drugField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Drug Bought");

        errorLabel.setForeground(new java.awt.Color(255, 0, 51));

        backbutt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icon.png"))); // NOI18N
        backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(searchButt)
                        .addGap(60, 60, 60)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameField)
                            .addComponent(idField)
                            .addComponent(patientCaseField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(perscribedByField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(69, 69, 69))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kebeleField, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(homeNoField)
                            .addComponent(phoneNoField)
                            .addComponent(drugField)
                            .addComponent(emailField))
                        .addGap(188, 188, 188))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButt)
                    .addComponent(backbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(drugField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(phoneNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientCaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(kebeleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perscribedByField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(homeNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void close() { 
    this.setVisible(false);
    this.dispose();
    } 
    public void setControl(int control){
        this.control =control; 
    }
    public int getControl(){
        return control;
    }
    
    private void searchButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtActionPerformed
        String name = searchField.getText();
        patientLinkedList list = new patientLinkedList();
        patient pat = list.searchList(name);
        if(list.getCounter()==0){
            JOptionPane.showMessageDialog(null, "add item first to search", "pharamacy managmnt system", JOptionPane.OK_OPTION);
        }
        else{
        if(pat==null){
            JOptionPane.showMessageDialog(null, "no items found by this name", "pharamacy managmnt system", JOptionPane.OK_OPTION);
        }
        else{
            nameField.setText(pat.getName());
            idField.setText(pat.getId());
            patientCaseField.setText(pat.getPatientCase());
            dateField.setText(pat.getDate());
            perscribedByField.setText(pat.getPerscribedBy());
            drugField.setText(pat.getDrug());
            phoneNoField.setText(pat.addr.getPhoneNumber());
            emailField.setText(pat.addr.getEmail());
            kebeleField.setText(String.valueOf(pat.addr.getKebele()));
            homeNoField.setText(String.valueOf(pat.addr.getHomeNumber()));
        }
        }
    }//GEN-LAST:event_searchButtActionPerformed

    private void kebeleFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kebeleFieldKeyTyped
       
    }//GEN-LAST:event_kebeleFieldKeyTyped

    private void homeNoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homeNoFieldKeyTyped
        
    }//GEN-LAST:event_homeNoFieldKeyTyped

    private void perscribedByFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perscribedByFieldKeyTyped
       
    }//GEN-LAST:event_perscribedByFieldKeyTyped

    private void dateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateFieldKeyTyped
        
    }//GEN-LAST:event_dateFieldKeyTyped

    private void idFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFieldKeyTyped
        
    }//GEN-LAST:event_idFieldKeyTyped

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        
    }//GEN-LAST:event_nameFieldKeyTyped

    private void addButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtActionPerformed
        if(nameField.getText().equals("")||idField.getText().equals("")||patientCaseField.getText().equals("")||perscribedByField.getText().equals("")
                ||drugField.getText().equals("")||phoneNoField.getText().equals("")||emailField.getText().equals("")||kebeleField.getText().equals("")
                ||homeNoField.getText().equals("")){
            
            errorLabel.setText("Error: every field must be field approperietly");
        }
       else{
            drugLinkedList list = new drugLinkedList();
            drug dr = list.searchList(drugField.getText());
            if(dr==null){
                errorLabel.setText("Error: the drug you enterd dosn't exist in the store");
            }
            else{
                String name = nameField.getText();
                String id = idField.getText();
                String patientCase = patientCaseField.getText();
                String perscribedBy = perscribedByField.getText();
                String drug = drugField.getText();
                String phoneNo = phoneNoField.getText();
                String email = emailField.getText();
                int kebele = Integer.parseInt(kebeleField.getText());
                int homeNo = Integer.parseInt(homeNoField.getText());

                    
                    address addr = new address(phoneNo,email,kebele,homeNo);
                    patient pat = new patient(name,id,patientCase,perscribedBy,drug,addr);
                    pat.addPatient(pat);
                    dateField.setText(pat.getDate());
                 DefaultTableModel model = (DefaultTableModel) jTable.getModel();

                 model.addRow( new Object[]{nameField.getText(),idField.getText(),patientCaseField.getText(),dateField.getText(),
                     perscribedByField.getText(),drugField.getText(),phoneNoField.getText(),emailField.getText(),kebeleField.getText(),
                     homeNoField.getText()});
             } 
        }
    }//GEN-LAST:event_addButtActionPerformed

    private void updateButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButt1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to update","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
              if(nameField.getText().equals("")||idField.getText().equals("")||patientCaseField.getText().equals("")||perscribedByField.getText().equals("")
                ||drugField.getText().equals("")||phoneNoField.getText().equals("")||emailField.getText().equals("")||kebeleField.getText().equals("")
                ||homeNoField.getText().equals("")){
            
            errorLabel.setText("Error: every field must be field approperietly");
        }
              else{
                drugLinkedList list = new drugLinkedList();
                drug dr = list.searchList(drugField.getText());
                if(dr==null){
                    errorLabel.setText("Error: the drug you enterd dosn't exist in the store");
                }
                else{  
                    String name = nameField.getText();
                    String id = idField.getText();
                    String patientCase = patientCaseField.getText();
                    String perscribedBy = perscribedByField.getText();
                    String drug = drugField.getText();
                    String phoneNo = phoneNoField.getText();
                    String email = emailField.getText();
                    int kebele = Integer.parseInt(kebeleField.getText());
                    int homeNo = Integer.parseInt(homeNoField.getText());




                    int row = jTable.getSelectedRow();
                    //System.out.println(row);
                    address addr = new address(phoneNo,email,kebele,homeNo);
                    patient pat = new patient(name,id,patientCase,perscribedBy,drug,addr);
                    patientLinkedList patientList  = new patientLinkedList();
                    patientList.update(row,pat);
                    String oldDate = String.valueOf(jTable.getValueAt(row,3));
                    jTable.setValueAt(name,row,0);
                    jTable.setValueAt(id,row,1);
                    jTable.setValueAt(patientCase,row,2);
                    jTable.setValueAt(oldDate,row,3);
                    jTable.setValueAt(perscribedBy,row,4);
                    jTable.setValueAt(drug,row,5);
                    jTable.setValueAt(phoneNo,row,6);
                    jTable.setValueAt(email,row,7);
                    jTable.setValueAt(kebele,row,8);
                    jTable.setValueAt(homeNo,row,9);
              }
            }
        }
    }//GEN-LAST:event_updateButt1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nameField.setText("");
        idField.setText("");
        patientCaseField.setText("");
        perscribedByField.setText("");
        drugField.setText("");
        phoneNoField.setText("");
        emailField.setText("");
        kebeleField.setText("");
        homeNoField.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void showButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to edit","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
           int x = jTable.getSelectedRow();
            nameField.setText(String.valueOf(jTable.getValueAt(x,0)));
            idField.setText(String.valueOf(jTable.getValueAt(x,1)));
            patientCaseField.setText(String.valueOf(jTable.getValueAt(x,2)));
            dateField.setText(String.valueOf(jTable.getValueAt(x,3)));
            perscribedByField.setText(String.valueOf(jTable.getValueAt(x,4)));
            drugField.setText(String.valueOf(jTable.getValueAt(x,5)));
            phoneNoField.setText(String.valueOf(jTable.getValueAt(x,6)));
            emailField.setText(String.valueOf(jTable.getValueAt(x,7))); 
            kebeleField.setText(String.valueOf(jTable.getValueAt(x,8)));
            homeNoField.setText(String.valueOf(jTable.getValueAt(x,9)));
        }
    }//GEN-LAST:event_showButtActionPerformed

    private void deleteButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        if(jTable.getSelectedRow()==-1){
            if(jTable.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"no data to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
            }
            else
                JOptionPane.showMessageDialog(null,"select a row to delete","pharmacy managmnet system",JOptionPane.OK_OPTION);
        }
        else{
            
            System.out.println(jTable.getSelectedRow());
            patientLinkedList list = new patientLinkedList();
            list.deleteAt(jTable.getSelectedRow());
            model.removeRow(jTable.getSelectedRow());
            
        }
    }//GEN-LAST:event_deleteButtActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        
    }//GEN-LAST:event_dateFieldActionPerformed

    private void backbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttActionPerformed
        if(control==1){
            new ownerUI().setVisible(true);
            close();
        }
        else if(control==2){
            new pharmacistUI().setVisible(true);
            close();
        }
    }//GEN-LAST:event_backbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patientUI(control).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButt;
    private javax.swing.JButton backbutt;
    private javax.swing.JButton clear;
    private javax.swing.JTextField dateField;
    private javax.swing.JButton deleteButt;
    private javax.swing.JTextField drugField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField homeNoField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField kebeleField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField patientCaseField;
    private javax.swing.JTextField perscribedByField;
    private javax.swing.JTextField phoneNoField;
    private javax.swing.JButton searchButt;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton showButt;
    private javax.swing.JButton updateButt1;
    // End of variables declaration//GEN-END:variables
}
